export const MACSKALISTA =[
    {
        nev:"Cirmi",
        kor:10,
        fajta:"Házimacska"
    },
    {
        nev:"Mió",
        kor:6,
        fajta:"Sziámi"
    },
    {
        nev:"Safranek",
        kor:6,
        fajta:"Maincoon"
    },
    {
        nev:"Csipesz",
        kor:8,
        fajta:"Házimacska"
    },
    {
        nev:"Zsebi",
        kor:8,
        fajta:"Házimacska"
    }
]
